FROM node:22-alpine

# Thiết lập thư mục làm việc
WORKDIR /app
# Sao chép các tệp cấu hình và phụ thuộc
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY .env .
COPY ./src ./src

# Cài đặt các phụ thuộc Node.js
RUN apk add --no-cache ffmpeg
RUN apk add python3
RUN npm install pm2 -g
RUN npm install
RUN npm run build

# Lắng nghe trên cổng 3000
EXPOSE 3000

# Chạy ứng dụng
CMD ["pm2", "start", "ecosystem.config.js"]
